name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Prepare BASE_PATH and optional CNAME
        shell: bash
        run: |
          if [[ -n "${{ vars.CUSTOM_DOMAIN }}" ]]; then
            echo "CUSTOM_DOMAIN=${{ vars.CUSTOM_DOMAIN }}" >> $GITHUB_ENV
            echo "BASE_PATH=/" >> $GITHUB_ENV
          else
            OWNER_REPO=${{ github.repository }}
            REPO_NAME=${OWNER_REPO#*/}
            if [[ "${REPO_NAME}" != "${{ github.repository_owner }}.github.io" ]]; then
              echo "BASE_PATH=/${REPO_NAME}/" >> $GITHUB_ENV
            else
              echo "BASE_PATH=/" >> $GITHUB_ENV
            fi
          fi

      - name: Build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
        run: |
          npm run build
          node scripts/postbuild.mjs
          if [[ -n "${CUSTOM_DOMAIN}" ]]; then echo "$CUSTOM_DOMAIN" > build/client/CNAME; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
