name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Prepare BASE_PATH and optional CNAME
        shell: bash
        run: |
          if [[ -n "${{ vars.CUSTOM_DOMAIN }}" ]]; then
            echo "CUSTOM_DOMAIN=${{ vars.CUSTOM_DOMAIN }}" >> $GITHUB_ENV
            echo "BASE_PATH=/" >> $GITHUB_ENV
          else
            OWNER_REPO=${{ github.repository }}
            REPO_NAME=${OWNER_REPO#*/}
            if [[ "${REPO_NAME}" != "${{ github.repository_owner }}.github.io" ]]; then
              echo "BASE_PATH=/${REPO_NAME}/" >> $GITHUB_ENV
            else
              echo "BASE_PATH=/" >> $GITHUB_ENV
            fi
          fi

      - name: Build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
        run: npm run build

      - name: Write CNAME (optional)
        if: env.CUSTOM_DOMAIN != ''
        run: echo "$CUSTOM_DOMAIN" > build/client/CNAME

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/client
          publish_branch: gh-pages
          enable_jekyll: false
          force_orphan: true
